name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file from GitHub Secrets
        run: |
          echo "REACT_APP_DATA_GET_URL=${{ secrets.REACT_APP_DATA_GET_URL }}" >> .env
          echo "REACT_APP_DATA_POST_URL=${{ secrets.REACT_APP_DATA_POST_URL }}" >> .env
          cat .env

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_DATA_GET_URL: ${{ secrets.REACT_APP_DATA_GET_URL }}
          REACT_APP_DATA_POST_URL: ${{ secrets.REACT_APP_DATA_POST_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync build folder to S3
        run: |
          aws s3 sync build/ s3://my-react-app-bucket-20250929/ --delete
